hostname: C000267-012S031P
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 192.168.100.31
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  bgp_defaults:
  - timers bgp 5 15
  - neighbor default send-community
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 128
    ecmp: 128
  updates:
    wait_install: true
  graceful_restart:
    enabled: true
    restart_time: 300
  peer_groups:
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    password: '{{ vault.bgp_peerings.overlay.password }}'
    send_community: all
    maximum_routes: 0
    remote_as: '65001'
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
  address_family_ipv4:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: false
  address_family_rtc:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  neighbors:
  - ip_address: 192.168.1.251
    peer_group: EVPN-OVERLAY-PEERS
    peer: C000267-009R601P
    description: C000267-009R601P
  - ip_address: 192.168.1.252
    peer_group: EVPN-OVERLAY-PEERS
    peer: C000267-014R602P
    description: C000267-014R602P
  as_notation: asdot
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 4096
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.131/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ntp:
  servers:
  - name: 0.pool.ntp.org
    vrf: default
    preferred: true
ethernet_interfaces:
- name: Ethernet1/1/1
  peer: C000267-009R601P
  peer_interface: Ethernet3/31/1
  peer_type: spine
  description: P2P_LINK_TO_C000267-009R601P_Ethernet3/31/1
  speed: forced 100g
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 192.168.3.121/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
- name: Ethernet2/1/1
  peer: C000267-014R602P
  peer_interface: Ethernet3/31/1
  peer_type: spine
  description: P2P_LINK_TO_C000267-014R602P_Ethernet3/31/1
  speed: forced 100g
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 192.168.3.123/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 192.168.100.31/32
  ospf_area: 0.0.0.0
- name: Loopback1
  description: VTEP_VXLAN_Tunnel_Source
  shutdown: false
  ip_address: 192.168.200.31/32
  ospf_area: 0.0.0.0
router_ospf:
  process_ids:
  - id: 100
    passive_interface_default: true
    router_id: 192.168.100.31
    max_lsa: 12000
    no_passive_interfaces:
    - Ethernet1/1/1
    - Ethernet2/1/1
    bfd_enable: false
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.200.31:1
router_bfd:
  multihop:
    interval: 3000
    min_rx: 3000
    multiplier: 3
route_maps:
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 192.168.200.31:1 additive
ip_igmp_snooping:
  globally_enabled: false
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vxlan_interface:
  Vxlan1:
    description: C000267-012S031P_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
metadata:
  platform: '758'
dhcp_relay:
  tunnel_requests_disabled: true
ip_name_servers:
- ip_address: 10.255.0.2
management_ssh:
  access_groups:
  - name: SNMP-ACL
    vrf: MGMT
  idle_timeout: 5
  enable: true
  vrfs:
  - name: MGMT
    enable: true
banners:
  login: '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    !!                                                                        !!

    !! IF THE COMPANY HAS NOT AUTHORISED YOUR ACCESS TO THIS SYSTEM YOU       !!

    !! WILL COMMIT A CRIMINAL OFFENCE IF YOU DO NOT IMMEDIATELY DISCONNECT.   !!

    !!                                                                        !!

    !! UNAUTHORISED ACCESS IS STRICTLY FORBIDDEN AND A DISCIPLINARY OFFENCE.  !!

    !!                                                                        !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    EOF

    '
