---
all:
  children:
    CLOUDVISION:
      hosts:
        CVaaS:
          ansible_host: www.cv-prod-us-central1-c.arista.io
          ansible_user: cvaas
          ansible_password: "{{ lookup('file', '{{ inventory_dir }}/CVaaS.token')}}"
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: True
          ansible_network_os: eos
        # cv_ztp:
          # Address of host that will act as DHCP server
          # ansible_host: 10.255.19.250
        # cv_server:
        #   # section for CVP primary node address
        #   ansible_httpapi_host: 10.255.19.250
        #   ansible_host: 10.255.19.250
        #   ansible_connection: httpapi
        #   ansible_httpapi_use_ssl: false
        #   ansible_httpapi_validate_certs: false
        #   ansible_network_os: eos
        #   ansible_httpapi_port: 443
        #   fabric_name: FABRIC
        #   # Configuration to get Virtual Env information
        #   ansible_python_interpreter: $(which python3)
    CAMPUS_GLOBAL:
      children:
        # node_groups indented below the fabric var will create containers
        CAMPUS_ASIA:
          children:
            LAB:
              children:
                LAB_SPINES:
                  hosts:
                    C000140-009R601P:
                      # ansible_host var required for validation role.
                      ansible_host: 192.168.0.251
                    C000140-014R602P:
                      ansible_host: 192.168.0.252
                LAB_LEAFS:
                  children:
                    LAB_WC_GRD:
                      hosts:
                        C000140-GRDS001P:
                          ansible_host: 192.168.0.101
                    LAB_WC_07:
                      hosts:
                        C000140-007S008P:
                          ansible_host: 192.168.0.108
                    LAB_SRV_LEAFS:
                      hosts:
                        C000140-009S560P:
                          ansible_host: 192.168.0.160
                        C000140-009S561P:
                          ansible_host: 192.168.0.161
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            # should use vault for passwords
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_port: 443
            ansible_httpapi_validate_certs: false

        NETWORK_SERVICES:
          children:
            LAB_SPINES:
            LAB_LEAFS:

        LAB_ENDPOINTS:
          children:
            LAB_LEAFS:
        