---
# local users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "{{ vault.users.admin.password }}"
  - name: cvpadmin
    privilege: 15
    role: network-admin
    sha512_password: "{{ vault.users.cvpadmin.password }}"

custom_structured_configuration_enable_password:
  hash_algorithm: sha512
  key: "{{ vault.enable.password }}"

# Cloud Vision server information
cvp_token_file: /tmp/token
cvp_instance_ips:
  - 192.168.0.5

# update overlay mtu for real deployment -> 9100
custom_structured_configuration_interface_defaults:
  mtu: 1500
  ethernet:
    shutdown: true

# adjust arp below mac aging timer as needed
custom_structured_configuration_arp:
  aging:
    timeout_default: 1500

mac_address_table:
  aging_time: 1800

custom_structured_configuration_switchport_default:
  mode: routed

custom_structured_configuration_management_console:
  idle_timeout: 100

custom_structured_configuration_errdisable:
  recovery:
    interval: 30

custom_structured_configuration_load_interval:
  default: 5

# custom_structured_configuration_terminal:
#  length: 60

custom_structured_configuration_ip_icmp_redirect: false

# DNS servers. In ACT, reachable via default.
# Cannot use eos_designs `name_servers` because mgmt_interface_vrf is MGMT
custom_structured_configuration_ip_name_servers:
  - ip_address: 10.255.0.2
#   vrf: MGMT

# NTP Servers IP or DNS name, first NTP server will be prefered
ntp_settings:
  server_vrf: default
  servers:
    - name: 0.pool.ntp.org

# Management SSH
custom_structured_configuration_management_ssh:
  access_groups:
    - name: SNMP-ACL
      vrf: MGMT
  idle_timeout: 5
  enable: true
  vrfs:
    - name: MGMT
      enable: true

custom_structured_configuration_ip_tacacs_source_interfaces:
  - name: Management1
    vrf: MGMT

custom_structured_configuration_aaa_authentication:
  login:
    default: local
    console: local
  policies:
    on_failure_log: true
    on_success_log: true

custom_structured_configuration_aaa_authorization:
  exec:
    default: local
  config_commands: true
  serial_console: true
  commands:
    all_default: local

# custom_structured_configuration_aaa_accounting:
#   exec:
#     default:
#       type: start-stop
#       group: TacServer
#   commands:
#     commands_default:
#       - commands: 0-15
#         type: start-stop
#         group: TacServer

# If using tacacs+, add your key in Global/vault file:
# custom_structured_configuration_tacacs_servers:
#   hosts:
#     - host: 1.2.3.4
#       vrf: mgmt
#       key: "{{ vault.tacacs.key }}"
#       key_type: 7

custom_structured_configuration_standard_access_lists:
  - name: SNMP-ACL
    sequence_numbers:
      - sequence: 10
        action: "permit 0.0.0.0/0"
  - name: CVP-ACL
    sequence_numbers:
      - sequence: 10
        action: "permit 0.0.0.0/0"

custom_structured_configuration_management_security:
  # entropy_source: hardware
  password:
    encryption_key_common: true

custom_structured_configuration_banners:
  login: |
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!                                                                        !!
    !! IF THE COMPANY HAS NOT AUTHORISED YOUR ACCESS TO THIS SYSTEM YOU       !!
    !! WILL COMMIT A CRIMINAL OFFENCE IF YOU DO NOT IMMEDIATELY DISCONNECT.   !!
    !!                                                                        !!
    !! UNAUTHORISED ACCESS IS STRICTLY FORBIDDEN AND A DISCIPLINARY OFFENCE.  !!
    !!                                                                        !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    EOF

# TODO - probably need a default ACL for this in eos_designs
custom_structured_configuration_management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    - name: MGMT
      access_group: CVP-ACL

internal_vlan_order:
  allocation: ascending
  range:
    beginning: 3500
    ending: 4000

timezone: US/Central

custom_structured_configuration_event_monitor:
  enabled: true
p2p_uplinks_mtu: 9214
# custom_structured_configuration_logging:
#   buffered:
#     size: 8000  # messages
#     level: notifications
#   trap: debugging
#   format:
#     timestamp: high-resolution
#     hostname: fqdn
#   vrfs:
#     - name: management
#       source_interface: Management1
#       hosts:
#         - name: 1.2.3.4
#           protocol: udp

# sflow config using CVP as sflow collector
# TODO have a look at https://avd.sh/en/stable/roles/eos_designs/docs/input-variables.html#sflow-settings
# custom_structured_configuration_sflow:
#   sample: 131072
#   destinations:
#     - 127.0.0.1
#   source_interface: Loopback0
#   run: true

# TODO - eos_designs will configure notifying based on `platform_settings.[].feature_support.queue_monitor_length_notify` setting.
# queue_monitor_length:
#  enabled: true
#  notifying: true

# custom_structured_configuration_queue_monitor_streaming:
#  enable: true

# snmp_settings:
#   enable_mgmt_interface_vrf: true
#   # engineID = use hostname + ip, by default
#   compute_local_engineid: true
#   compute_v3_user_localized_key: true
#   groups:
#     - name: arista_snmp_group
#       version: v3
#       authentication: priv
#   users:
#     - name: arista_snmp
#       group: arista_snmp_group
#       version: v3
#       auth: sha
#       auth_passphrase: "{{ vault.snmpv3.users.user1.auth }}"
#       priv: aes
#       priv_passphrase: "{{ vault.snmpv3.users.user1.priv }}"
#   hosts:
#     - host: 1.2.3.4
#       vrf: MGMT
#       version: 3
#       users:
#         - username: arista_snmp
#           authentication_level: priv
#   traps:
#     enable: true
evpn_hostflap_detection:

  # If set to false it will disable EVPN host-flap detection.
  enabled: True