---
ztp:
  default:
    registration: http://10.88.160.137/ztp/bootstrap
    gateway: 10.88.172.161
    nameservers:
      - 10.88.160.61
    use_system_mac: true
  general:
    subnets:
      - network: 10.88.172.160
        netmask: 255.255.255.224
        gateway: 10.88.172.161
        nameservers:
          - 10.88.160.61
        start: 10.88.172.191
        end: 10.88.172.191
        lease_time: 300
  clients:
    # l3leaf
    # spine
    - name: DC1-SP1
      mac: '0c:1d:c0:1d:62:01'
      ip4: 10.88.172.162
    - name: DC1-SP2
      mac: '0c:1d:c0:1d:62:02'
      ip4: 10.88.172.163
