---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: CAMPUS_GLOBAL
dc_name: LAB

# mgmt_gateway: 10.255.0.1 //commented for ACT

underlay_routing_protocol: OSPF
evpn_multicast: true
underlay_multicast: true

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false
# Default gateway used for the management interface
mgmt_gateway: 192.168.0.1


# Enable RT membership
evpn_overlay_bgp_rtc: true

default_interfaces:
  - types: [ spine ]
    platforms: [ 7304-x3 ]
    downlink_interfaces: [ Ethernet3/1-31/1,Ethernet4/1-31/1 ]
  - types: [ l3leaf ]
    platforms: [ 720XP-48 ]
    uplink_interfaces: [ Ethernet53/1, Ethernet54/1 ]
    # downlink_interfaces: [ Ethernet1-48 ]
  - types: [ l3leaf ]
    platforms: [ "758" ]
    uplink_interfaces: [ Ethernet1/1/1,Ethernet2/1/1 ]
    # downlink_interfaces: [ Ethernet8 ]
  - types: [ service_leaf ]
    platforms: [ "7050TX3-48" ]
    uplink_interfaces: [ Ethernet1/1/1,Ethernet2/1/1 ]
    mlag_interfaces: [ Ethernet1/1/2,Ethernet2/1/2 ]
    # downlink_interfaces: [ Ethernet8 ]
platform_settings:
  - platforms: ['default']
  - platforms: ['720XP-48', '720XP-96']
    trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 24000 l3-shared 24000"
  - platforms: ['7050TX3-48', '7050SX3-48']
    trident_forwarding_table_partition: "flexible exact-match 16384 l2-shared 98304 l3-shared 131072"
  - platforms: ['758']
    trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 24000 l3-shared 24000"
node_type_keys:
  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    default_ptp_priority1: 30
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
      
  - key: spine
    type: spine
    # super-spines are route reflectors
    default_evpn_role: server
    # super-spines are also fabric borders, need L3 interfaces
    network_services:
      l3: true
    vtep: true

  - key: service_leaf
    type: service_leaf
    default_evpn_role: client
    mlag_support: true
    # super-spines are also fabric borders, need L3 interfaces
    network_services:
      l3: true
      l2: true
    vtep: true

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "{{ vault.bgp_peerings.underlay.password }}"
    structured_config:
      session_tracker: TRACKER
  evpn_overlay_peers:
    password: "{{ vault.bgp_peerings.overlay.password }}"
  mlag_ipv4_underlay_peer:
    password: "{{ vault.bgp_peerings.mlag.password }}"

# BGP defaults
bgp_maximum_paths: 128
bgp_ecmp: 128
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200
bgp_graceful_restart:
  enabled: true
  restart_time: 300
# BGP update wait commands will be disabled for vEOS
bgp_update_wait_install: true
overlay_routing_protocol: ibgp
# Spine Switches
new_network_services_bgp_vrf_config: true
spine:
  defaults:
    platform: 7304-x3
    bgp_as: "65001"
    loopback_ipv4_pool: 192.168.1.0/24
    # loopback_ipv4_offset: 250
    loopback_ipv6_pool: 2001:db8:abcd:0012::/64
    vtep_loopback_ipv4_pool: 192.168.203.0/24
    structured_config:
      router_bgp:
        as_notation: "asdot"
    bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community
  nodes:
    - name: C000140-001R601A
      id: 251
      filter:
        tags: [ C000140-001R601A, LAB_SPINES ]
        always_include_vrfs_in_tenants: [ all ]
      mgmt_ip: 192.168.0.251/24
    - name: C000140-001R602A
      id: 252
      filter:
        tags: [ C000140-001R601A, LAB_SPINES ]
      mgmt_ip: 192.168.0.252/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: EOS
    bgp_as: "65001"
    uplink_ipv4_pool: 192.168.3.0/24
    # uplink_ipv6_pool: 2001:db8:abcd:0012/64
    loopback_ipv4_pool: 192.168.100.0/24
    vtep_loopback_ipv4_pool: 192.168.200.0/24
    uplink_switches: [ C000140-001R601A ]
    # uplink_interface_speed: forced 100g
    mlag: false
    mlag_peer_ipv4_pool: 192.168.2.0/25
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 192.168.2.128/25
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    inband_mgmt_interface: Loopback0
    structured_config:
      router_bgp:
        as_notation: "asdot"
      dhcp_relay:
        tunnel_requests_disabled: true
    bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community

  node_groups:
    - group: LAB_WC_GRD
      filter:
        tags: [ LAB_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000140-001R601A , C000140-001R602A ]
      platform: 720XP-48
      nodes:
        - name: C000140-001S001A
          filter:
            tags: [ C000140-001S001A, LAB_LEAFS ]
          id: 1
          mgmt_ip: 192.168.0.101/24
        - name: C000140-001S002A
          filter:
            tags: [ C000140-001S002A, LAB_LEAFS ]
          id: 2
          mgmt_ip: 192.168.0.102/24  
    - group: LAB_WC_07
      filter:
        tags: [ LAB_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000140-001R601A , C000140-001R602A ]
      platform: 758
      nodes:
        - name: C000140-001S003A
          filter:
            tags: [ C000140-001S003A, LAB_LEAFS ]
          id: 3
          mgmt_ip: 192.168.0.103/24
        - name: C000140-001S004A
          filter:
            tags: [ C000140-001S004A, LAB_LEAFS ]
          id: 4
          mgmt_ip: 192.168.0.104/24  
service_leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: EOS
    bgp_as: "65001"
    uplink_ipv4_pool: 192.168.3.0/24
    # uplink_ipv6_pool: 2001:db8:abcd:0012/64
    loopback_ipv4_pool: 192.168.100.0/24
    vtep_loopback_ipv4_pool: 192.168.210.0/24
    uplink_switches: [C000140-001R601A , C000140-001R602A]
    # uplink_interface_speed: forced 100g
    mlag: true
    mlag_peer_ipv4_pool: 192.168.2.0/25
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 192.168.2.128/25
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    inband_mgmt_interface: Loopback0
    structured_config:
      router_bgp:
        as_notation: "asdot"
      dhcp_relay:
        tunnel_requests_disabled: true
    bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community
  node_groups:
    - group: LAB_SRV_LEAFS
      filter:
        tags: [ LAB_LEAFS ]
      # vtep_loopback_ipv4_pool: 167.84.63.80/24
      uplink_switches: [ C000140-001R601A, C000140-001R602A ]
      platform: 7050TX3-48
      nodes:
        - name: C000140-001S560A
          filter:
            tags: [ C000140-001S560A, LAB_SERVICE_LEAFS ]
          id: 5
          mgmt_ip: 192.168.0.160/24
        - name: C000140-001S561A
          filter:
            tags: [ C000140-001S561A, LAB_SERVICE_LEAFS ]
          id: 6
          mgmt_ip: 192.168.0.161/24
    # TODO should service leaf become its own "type"?
# update mtu for real deployment -> 9214

# Adjust default bfd values
bfd_multihop:
  interval: 3000
  min_rx: 3000
  multiplier: 3

svi_profiles:
  - profile: OVERLAY_SVI
    enabled: true
    # igmp snooping is not enabled in existing configs
    # igmp_snooping_enabled: true
    # ip_helpers:
      # 10.0.10.10:
        # source_interface: Loopback0
        # source_vrf: default
  - profile: INTERNAL_default
    parent_profile: OVERLAY_SVI
  - profile: IOTBMS_default
    parent_profile: OVERLAY_SVI
