---
type: l3leaf
dot1x:
  system_auth_control: true
  aaa:
    unresponsive:
      action:
        traffic_allow: true

management_api_gnmi:
  transport:
    grpc:
      - name: default
        vrf: default

interface_defaults:
  mtu: 9214

ip_dhcp_relay:
  information_option: true

# uncomment if dchp relay is enabled in the vteps.
# custom_structured_configuration_dhcp_relay:
#   tunnel_requests_disabled: true
#   mlag_peerlink_requests_disabled: true
