---
port_profiles:
  - profile: endpoint_access_dot1x
    description: Endpoint access port (Dot1x enabled)
    native_vlan: 301
    mode: trunk phone
    mtu: 1500
    dot1x:
      port_control: auto
      reauthentication: true 
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true 
      mac_based_authentication:
        enabled: true
        host_mode_common: true 
      timeout:
        tx_period: 10
      authentication_failure:
        action: allow
        allow_vlan: 601
    spanning_tree_bpduguard: true
    storm_control:
      broadcast:
        level: 1
    # Need POE settings, and storm control, etc when decided
  - profile: wifi_access_point
    description: Access Point port
    mode: access
    spanning_tree_bpduguard: true
    storm_control:
      broadcast:
        level: 1
  - profile: trunk_port
    description: Trunk Port All VLANs
    mode: trunk
    storm_control:
      broadcast:
        level: 10
  - profile: access_port
    description: Access Port
    mode: access
    storm_control:
      broadcast:
        level: 10  
  - profile: test_port
    description: TEST_PORT FOR DATA AND VOICE
    native_vlan: 301
    mode: trunk phone
    mtu: 1500
    spanning_tree_bpduguard: true
    storm_control:
      broadcast:
        level: 1
    # Need POE settings, and storm control, etc when decided
  - profile: bms_five_twenty
    description: BMS_PORT
    mode: access
    vlans: "520"
    # spanning_tree_bpduguard: true
    # storm_control:
    #   broadcast:
    #     level: 10
    dot1x:
      port_control: auto
      reauthentication: true 
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true 
      mac_based_authentication:
        enabled: true
        host_mode_common: true 
      timeout:
        tx_period: 10
      authentication_failure:
        action: allow
        allow_vlan: 601
    spanning_tree_bpduguard: true
    storm_control:
      broadcast:
        level: 1
  - profile: bms_five_twentyone
    description: BMS_PORT
    mode: access
    vlans: "521"
    # spanning_tree_bpduguard: true
    # storm_control:
    #   broadcast:
    #     level: 10
    dot1x:
      port_control: auto
      reauthentication: true 
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true 
      mac_based_authentication:
        enabled: true
        host_mode_common: true 
      timeout:
        tx_period: 10
      authentication_failure:
        action: allow
        allow_vlan: 601
    spanning_tree_bpduguard: true
    storm_control:
      broadcast:
        level: 1

network_ports:
  - switches:
      - C000267-GRDS001P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS002P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS003P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS004P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS005P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS006P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-GRDS007P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-007S008P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-007S009P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-007S010P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-007S011P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-008S012P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-008S013P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-008S014P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-008S015P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-009S016P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-009S017P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-009S018P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-009S019P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-010S020P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-010S021P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-010S022P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-010S023P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-011S024P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-011S025P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-011S026P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-011S027P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x
 
  - switches:
      - C000267-012S028P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-012S029P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-012S030P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-012S031P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x
 
  - switches:
      - C000267-014S032P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-014S033P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-014S034P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-014S035P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x
  
  - switches:
      - C000267-015S036P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-015S037P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-015S038P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-015S039P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-016S040P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-016S041P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-016S042P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-016S043P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-017S044P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-017S045P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-017S046P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-017S047P
    switch_ports:
      - Ethernet1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-018S048P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-018S049P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-018S050P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-018S051P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-019S052P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-019S053P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-019S054P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-019S055P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-020S056P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-020S057P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-020S058P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x

  - switches:
      - C000267-020S059P
    switch_ports:
      - Ethernet3/1-48
      - Ethernet4/1-48
      - Ethernet5/1-48
      - Ethernet6/1-48
      - Ethernet7/1-48
      - Ethernet8/1-48
    profile: endpoint_access_dot1x
     

  ################################## Addeing southbound for vlan 520 and 521###############