---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: CAMPUS_GLOBAL
dc_name: MANILA

# mgmt_gateway: 10.255.0.1 //commented for ACT

underlay_routing_protocol: OSPF

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false

# Enable RT membership
evpn_overlay_bgp_rtc: true

# Disable igmp snooping default
default_igmp_snooping_enabled: false
default_interfaces: 
  - types: [ spine ]
    platforms: [ default ]
    downlink_interfaces: [ Ethernet3/1-31/1,Ethernet4/1-31/1 ]
  - types: [ l3leaf ]
    platforms: [ 720XP-48 ]
    uplink_interfaces: [ Ethernet53/1, Ethernet54/1 ]
    # downlink_interfaces: [ Ethernet1-48 ]
  - types: [ l3leaf ]
    platforms: [ "758" ]
    uplink_interfaces: [ Ethernet1/1/1,Ethernet2/1/1 ]
    # downlink_interfaces: [ Ethernet8 ]
  - types: [ l3leaf ]
    platforms: [ "7050TX3-48" ]
    uplink_interfaces: [ Ethernet1/1/1,Ethernet2/1/1 ]
    # downlink_interfaces: [ Ethernet8 ]
platform_settings:
  - platforms: ['default']
  - platforms: ['720XP-48', '720XP-96']
    trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 24000 l3-shared 24000"
  - platforms: ['7050TX3-48', '7050SX3-48']
    trident_forwarding_table_partition: "flexible exact-match 16384 l2-shared 98304 l3-shared 131072"
  - platforms: ['758']
    trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 24000 l3-shared 24000"


# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "{{ vault.bgp_peerings.underlay.password }}"
  evpn_overlay_peers:
    password: "{{ vault.bgp_peerings.overlay.password }}"
  mlag_ipv4_underlay_peer:
    password: "{{ vault.bgp_peerings.mlag.password }}"

# BGP defaults
bgp_maximum_paths: 128
bgp_ecmp: 128
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200
bgp_graceful_restart:
  enabled: true
  restart_time: 300
# BGP update wait commands will be disabled for vEOS
bgp_update_wait_install: true
overlay_routing_protocol: ibgp
# Spine Switches
spine:
  defaults:
    platform: EOS
    bgp_as: "65001"
    loopback_ipv4_pool: 192.168.1.0/24
    # loopback_ipv4_offset: 250
    loopback_ipv6_pool: 2001:db8:abcd:0012::/64
    structured_config:
      router_bgp:
        as_notation: "asdot"
    bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community

  nodes:
    - name: C000267-009R601P
      id: 251
      mgmt_ip: 192.168.0.200/24
    - name: C000267-014R602P
      id: 252
      mgmt_ip: 192.168.0.201/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: EOS
    bgp_as: "65001"
    uplink_ipv4_pool: 192.168.3.0/24
    # uplink_ipv6_pool: 2001:db8:abcd:0012/64
    loopback_ipv4_pool: 192.168.100.0/24
    vtep_loopback_ipv4_pool: 192.168.200.0/24
    uplink_switches: [C000267-014R601P, C000267-014R602P]
    uplink_interface_speed: forced 100g
    mlag: false
    mlag_peer_ipv4_pool: 192.168.2.0/25
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 192.168.2.128/25
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    inband_mgmt_interface: Loopback0
    structured_config:
      router_bgp:
        as_notation: "asdot"
      dhcp_relay:
        tunnel_requests_disabled: true
    bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community
    
  node_groups:
    - group: MANILA_WC_GRD
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 720XP-48 
      nodes:
        - name: C000267-GRDS001P
          filter:
            tags: [ C000267-GRDS001P, MANILA_LEAFS ]
          id: 1
          mgmt_ip: 192.168.0.101/24
        - name: C000267-GRDS002P
          filter:
            tags: [ C000267-GRDS002P, MANILA_LEAFS ]
          id: 2
          mgmt_ip: 192.168.0.102/24
        - name: C000267-GRDS003P
          filter:
            tags: [ C000267-GRDS003P, MANILA_LEAFS ]
          id: 3
          mgmt_ip: 192.168.0.103/24
        - name: C000267-GRDS004P
          filter:
            tags: [ C000267-GRDS004P, MANILA_LEAFS ]
          id: 4
          mgmt_ip: 192.168.0.104/24
        - name: C000267-GRDS005P
          filter:
            tags: [ C000267-GRDS005P, MANILA_LEAFS ]
          id: 5
          mgmt_ip: 192.168.0.105/24
        - name: C000267-GRDS006P
          filter:
            tags: [ C000267-GRDS006P, MANILA_LEAFS ]
          id: 6
          mgmt_ip: 192.168.0.106/24
        - name: C000267-GRDS007P
          filter:
            tags: [ C000267-GRDS007P, MANILA_LEAFS ]
          id: 7
          mgmt_ip: 192.168.0.107/24
    - group: MANILA_WC_7
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758 
      nodes:
        - name: C000267-007S008P
          filter:
            tags: [ C000267-007S008P, MANILA_LEAFS ]
          id: 8
          mgmt_ip: 192.168.0.108/24
        - name: C000267-007S009P
          filter:
            tags: [ C000267-007S009P, MANILA_LEAFS ]
          id: 9
          mgmt_ip: 192.168.0.109/24
        - name: C000267-007S010P
          filter:
            tags: [ C000267-007S010P, MANILA_LEAFS ]
          id: 10
          mgmt_ip: 192.168.0.110/24
        - name: C000267-007S011P
          filter:
            tags: [ C000267-007S011P, MANILA_LEAFS ]
          id: 11
          mgmt_ip: 192.168.0.111/24
    - group: MANILA_WC_8
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758 
      nodes:
        - name: C000267-008S012P
          filter:
            tags: [ C000267-008S012P, MANILA_LEAFS ]
          id: 12
          mgmt_ip: 192.168.0.112/24
        - name: C000267-008S013P
          filter:
            tags: [ C000267-008S013P, MANILA_LEAFS ]
          id: 13
          mgmt_ip: 192.168.0.113/24
        - name: C000267-008S014P
          filter:
            tags: [ C000267-008S014P, MANILA_LEAFS ]
          id: 14
          mgmt_ip: 192.168.0.114/24
        - name: C000267-008S015P
          filter:
            tags: [ C000267-008S015P, MANILA_LEAFS ]
          id: 15
          mgmt_ip: 192.168.0.115/24
    - group: MANILA_WC_9
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-009S016P
          filter:
            tags: [ C000267-009S016P, MANILA_LEAFS ]
          id: 16
          mgmt_ip: 192.168.0.116/24
        - name: C000267-009S017P
          filter:
            tags: [ C000267-009S017P, MANILA_LEAFS ]
          id: 17
          mgmt_ip: 192.168.0.117/24
        - name: C000267-009S018P
          filter:
            tags: [ C000267-009S018P, MANILA_LEAFS ]
          id: 18
          mgmt_ip: 192.168.0.118/24
        - name: C000267-009S019P
          filter:
            tags: [ C000267-009S019P, MANILA_LEAFS ]
          id: 19
          mgmt_ip: 192.168.0.119/24
    - group: MANILA_WC_10
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-010S020P
          filter:
            tags: [ C000267-010S020P, MANILA_LEAFS ]
          id: 20
          mgmt_ip: 192.168.0.120/24
        - name: C000267-010S021P
          filter:
            tags: [ C000267-010S021P, MANILA_LEAFS ]
          id: 21
          mgmt_ip: 192.168.0.121/24
        - name: C000267-010S022P
          filter:
            tags: [ C000267-010S022P, MANILA_LEAFS ]
          id: 22
          mgmt_ip: 192.168.0.122/24
        - name: C000267-010S023P
          filter:
            tags: [ C000267-010S023P, MANILA_LEAFS ]
          id: 23
          mgmt_ip: 192.168.0.123/24
    - group: MANILA_WC_11
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-011S024P
          filter:
            tags: [ C000267-011S024P, MANILA_LEAFS ]
          id: 24
          mgmt_ip: 192.168.0.124/24
        - name: C000267-011S025P
          filter:
            tags: [ C000267-011S025P, MANILA_LEAFS ]
          id: 25
          mgmt_ip: 192.168.0.125/24
        - name: C000267-011S026P
          filter:
            tags: [ C000267-011S026P, MANILA_LEAFS ]
          id: 26
          mgmt_ip: 192.168.0.126/24
        - name: C000267-011S027P
          filter:
            tags: [ C000267-011S027P, MANILA_LEAFS ]
          id: 27
          mgmt_ip: 192.168.0.127/24 
    - group: MANILA_WC_12
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758 
      nodes:
        - name: C000267-012S028P
          filter:
            tags: [ C000267-012S028P, MANILA_LEAFS ]
          id: 28
          mgmt_ip: 192.168.0.128/24
        - name: C000267-012S029P
          filter:
            tags: [ C000267-012S029P, MANILA_LEAFS ]
          id: 29
          mgmt_ip: 192.168.0.129/24
        - name: C000267-012S030P
          filter:
            tags: [ C000267-012S030P, MANILA_LEAFS ]
          id: 30
          mgmt_ip: 192.168.0.130/24
        - name: C000267-012S031P
          filter:
            tags: [ C000267-012S031P, MANILA_LEAFS ]
          id: 31
          mgmt_ip: 192.168.0.131/24
    - group: MANILA_WC_14
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-014S032P
          filter:
            tags: [ C000267-014S032P, MANILA_LEAFS ]
          id: 32
          mgmt_ip: 192.168.0.132/24
        - name: C000267-014S033P
          filter:
            tags: [ C000267-014S033P, MANILA_LEAFS ]
          id: 33
          mgmt_ip: 192.168.0.133/24
        - name: C000267-014S034P
          filter:
            tags: [ C000267-014S034P, MANILA_LEAFS ]
          id: 34
          mgmt_ip: 192.168.0.134/24
        - name: C000267-014S035P
          filter:
            tags: [ C000267-014S035P, MANILA_LEAFS ]
          id: 35
          mgmt_ip: 192.168.0.135/24
    - group: MANILA_WC_15
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-015S036P
          filter:
            tags: [ C000267-015S036P, MANILA_LEAFS ]
          id: 36
          mgmt_ip: 192.168.0.136/24
        - name: C000267-015S037P
          filter:
            tags: [ C000267-015S037P, MANILA_LEAFS ]
          id: 37
          mgmt_ip: 192.168.0.137/24
        - name: C000267-015S038P
          filter:
            tags: [ C000267-015S038P, MANILA_LEAFS ]
          id: 38
          mgmt_ip: 192.168.0.138/24
        - name: C000267-015S039P
          filter:
            tags: [ C000267-015S039P, MANILA_LEAFS ]
          id: 39
          mgmt_ip: 192.168.0.139/24
    - group: MANILA_WC_16
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-016S040P
          filter:
            tags: [ C000267-016S040P, MANILA_LEAFS ]
          id: 40
          mgmt_ip: 192.168.0.140/24
        - name: C000267-016S041P
          filter:
            tags: [ C000267-016S041P, MANILA_LEAFS ]
          id: 41
          mgmt_ip: 192.168.0.141/24
        - name: C000267-016S042P
          filter:
            tags: [ C000267-016S042P, MANILA_LEAFS ]
          id: 42
          mgmt_ip: 192.168.0.142/24
        - name: C000267-016S043P
          filter:
            tags: [ C000267-016S043P, MANILA_LEAFS ]
          id: 43
          mgmt_ip: 192.168.0.143/24  
    - group: MANILA_WC_17
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 720XP-48 
      nodes:
        - name: C000267-017S044P
          filter:
            tags: [ C000267-017S044P, MANILA_LEAFS ]
          id: 44
          mgmt_ip: 192.168.0.144/24
        - name: C000267-017S045P
          filter:
            tags: [ C000267-017S045P, MANILA_LEAFS ]
          id: 45
          mgmt_ip: 192.168.0.145/24
        - name: C000267-017S046P
          filter:
            tags: [ C000267-017S046P, MANILA_LEAFS ]
          id: 46
          mgmt_ip: 192.168.0.146/24
        - name: C000267-017S047P
          filter:
            tags: [ C000267-017S047P, MANILA_LEAFS ]
          id: 47
          mgmt_ip: 192.168.0.147/24
    - group: MANILA_WC_18
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 720XP-48
      nodes:
        - name: C000267-018S048P
          filter:
            tags: [ C000267-018S048P, MANILA_LEAFS ]
          id: 48
          mgmt_ip: 192.168.0.148/24
        - name: C000267-018S049P
          filter:
            tags: [ C000267-018S049P, MANILA_LEAFS ]
          id: 49
          mgmt_ip: 192.168.0.149/24
        - name: C000267-018S050P
          filter:
            tags: [ C000267-018S050P, MANILA_LEAFS ]
          id: 50
          mgmt_ip: 192.168.0.150/24
        - name: C000267-018S051P
          filter:
            tags: [ C000267-018S051P, MANILA_LEAFS ]
          id: 51
          mgmt_ip: 192.168.0.151/24  
    - group: MANILA_WC_19
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-019S052P
          filter:
            tags: [ C000267-019S052P, MANILA_LEAFS ]
          id: 52
          mgmt_ip: 192.168.0.152/24
        - name: C000267-019S053P
          filter:
            tags: [ C000267-019S053P, MANILA_LEAFS ]
          id: 53
          mgmt_ip: 192.168.0.153/24
        - name: C000267-019S054P
          filter:
            tags: [ C000267-019S054P, MANILA_LEAFS ]
          id: 54
          mgmt_ip: 192.168.0.154/24
        - name: C000267-019S055P
          filter:
            tags: [ C000267-019S055P, MANILA_LEAFS ]
          id: 55
          mgmt_ip: 192.168.0.155/24
    - group: MANILA_WC_20
      filter:
        tags: [ MANILA_LEAFS ]
      #loopback_ipv4_pool: 192.168.100.0/24
      # vtep loopback pool will not actually be used as we set Loopback0 as vtep sourceabove
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 758
      nodes:
        - name: C000267-020S056P
          filter:
            tags: [ C000267-020S056P, MANILA_LEAFS ]
          id: 56
          mgmt_ip: 192.168.0.156/24
        - name: C000267-020S057P
          filter:
            tags: [ C000267-020S057P, MANILA_LEAFS ]
          id: 57
          mgmt_ip: 192.168.0.157/24
        - name: C000267-020S058P
          filter:
            tags: [ C000267-020S058P, MANILA_LEAFS ]
          id: 58
          mgmt_ip: 192.168.0.158/24
        - name: C000267-020S059P
          filter:
            tags: [ C000267-020S059P, MANILA_LEAFS ]
          id: 59
          mgmt_ip: 192.168.0.159/24          
    - group: MANILA_SERVICE_LEAFS
      filter:
        tags: [ MANILA_LEAFS ]
      # vtep_loopback_ipv4_pool: 167.84.63.80/24               
      uplink_switches: [ C000267-009R601P, C000267-014R602P ]
      platform: 7050TX3-48 
      nodes:
        - name: C000267-009S560P
          filter:
            tags: [ C000267-009S560P, MANILA_LEAFS  ]
          id: 60
          mgmt_ip: 192.168.0.160/24
        - name: C000267-009S561P
          filter:
            tags: [ C000267-009S561P, MANILA_LEAFS ]
          id: 61
          mgmt_ip: 192.168.0.161/24
    # TODO should service leaf become its own "type"?
# update mtu for real deployment -> 9214
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 3000
  min_rx: 3000
  multiplier: 3
