---
# tenant_a Networks
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: JPMC-CAMPUS
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    # Force change
    mac_vrf_vni_base: 10000
    evpn_l3_multicast:
      enabled: true
      evpn_underlay_l3_multicast_group_ipv4_pool: 239.255.3.0/20
    pim_rp_addresses:
      - rps: [169.82.66.226]
        nodes: [ C000140-DCS-7304X3 ]
        groups: [ 224.0.0.0/4 ]
      - rps: [169.82.66.226]
        nodes: [ C000140-DCS-7304X3 ]
        groups: [ 239.1.0.0/16 ]
    vrfs:
      # VRF definitions inside the tenant.
      - name: VRF_INTERNAL
        # VRF VNI definition.
        vrf_vni: 101
        evpn_l3_multicast:
          enabled: true

        bgp_peer_groups:
          - name: SD_WAN_EDGE
            nodes: [ C000140-DCS-7304X3 ]
            address_family_ipv4:
              activate: true
            type: ipv4
            remote_as: 65201
            bfd: true
            maximum_routes: 0
            send_community: all
          # - name: SD_WAN_EDGE_IPV6
          #   nodes: [ C000140-DCS-7304X3, C000140-014R602P ]
          #   address_family_ipv6:
          #     activate: true
          #   type: ipv6
          #   remote_as: 65201
          #   bfd: true
          #   maximum_routes: 0
          #   send_community: all
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 10
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 167.84.63.0/24
        structured_config:
          ipv6_unicast_routing: true
        # #bgp:
        #  # structured_config:
        #    # aggregate_addresses:
        #       - prefix: 10.131.0.0/16
        #         summary_only: True
        svis:
          #SVI definitions.
          - id: 301
            #vni_override: 60301

            # Get basic settings from this profile defined in LAB.yml
            profile: INTERNAL_default
            # SVI description.
            name: C000140-Lab-Data

            tags: [ C000140-CCS-720XP ]
            ip_address_virtual: 10.67.1.1/24
            ip_helpers:
            - ip_helper: 169.86.42.132
            - ip_helper: 169.86.42.100
            # ipv6_address_virtuals:
            #   - fd00:82:0::1/64
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
          - id: 302
            #vni_override: 80301
            # Get basic settings from this profile defined in LAB.yml
            profile: INTERNAL_default
            # SVI description.
            name: C000140-Lab-Data

            tags: [ C000140-CCS-758 ]
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 10.67.2.1/24
            ip_helpers:
            - ip_helper: 169.86.42.132
            - ip_helper: 169.86.42.100
            # ipv6_address_virtuals:
            #   - fd00:82:0::1/64
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
          # - id: 500
          #   #vni_override: 65301
          #   # Get basic settings from this profile defined in LAB.yml
          #   profile: INTERNAL_default
          #   # SVI description.
          #   name: Mistedge
          #   tags: [ LAB_SERVICE_LEAFS ]
          #   # IP anycast gateway to be used in the SVI in every leaf.
          #   ip_address_virtual: 169.85.74.1/29
          #   # ip_helpers:
          #   # - ip_helper: 169.86.42.132
          #   # - ip_helper: 169.86.42.100
          #   # - ip_helper: 169.127.105.84
          #   # - ip_helper: 169.98.141.207
          #   # - ip_helper: 202.40.72.61
          #   # - ip_helper: 202.40.73.61
          #   # - ip_helper: 169.101.114.67
          #   # - ip_helper: 169.104.25.67
          #   ipv6_address_virtuals:
          #     - fd00:83:0::1/64
          #   bgp:
          #     structured_config:
          #       redistribute_routes: [ dot1x ]
        l3_interfaces:
          # Need to break these out into individual configs to accomodate ipv6 addresses which aren't modeled in l3_interfaces
          # BorderSpine 1 to ASR01 - VLAN 100
          - interfaces: [Ethernet3/32/1.100]
            encapsulation_dot1q_vlan: [100]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.26/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/0/1_VRF_INTERNAL
            pim:
              enabled: true
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:4::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR01 - VLAN 100
          - interfaces: [Ethernet3/32/1.100]
            encapsulation_dot1q_vlan: [100]
            nodes: [C000140-014R602P]
            ip_addresses: [10.12.46.8/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/1/5_VRF_INTERNAL
            pim:
              enabled: true
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:1::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 1 to ASR02 - VLAN 100
          - interfaces: [Ethernet4/32/1.100]
            encapsulation_dot1q_vlan: [100]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.0/31]
            description: P2P_LINK_TO_C160479-003R630A_Gi0/0/1_VRF_INTERNAL
            pim:
              enabled: true
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:10::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR02 - VLAN 100
          - interfaces: [Ethernet4/32/1.100]
            encapsulation_dot1q_vlan: [100]
            nodes: [C000140-014R602P]
            ip_addresses: [10.12.46.16/31]
            description: P2P_LINK_TO_C160479-003R630A_Gi0/1/5_VRF_INTERNAL
            pim:
              enabled: true
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:7::1/127
              flow_tracker:
                sampled: ftr_sampled
        bgp_peers:
          # - ip_address: "2000:10:2:4::"
          #   nodes: [ C000140-DCS-7304X3 ]
          #   description: C000140-CSG5000A
          #   peer_group: SD_WAN_EDGE_IPV6
          # - ip_address: "2000:10:2:10::"
          #   nodes: [ C000140-DCS-7304X3 ]
          #   description: C000140-CSG5000B
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:16:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:22:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # - ip_address: "2000:10:2:1::"
          #   nodes: [ C000140-014R602P ]
          #   description: C000140-CSG5000A
          #   peer_group: SD_WAN_EDGE_IPV6
          # - ip_address: "2000:10:2:7::"
          #   nodes: [ C000140-014R602P ]
          #   description: C000140-CSG5000B
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:13:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:19:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # - ip_address: 10.12.46.27
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # - ip_address: 10.12.46.1
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.16.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.22.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # - ip_address: 10.12.46.9
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE
          # - ip_address: 10.12.46.17
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.13.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.19.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: sd_wan_edge
      - name: VRF_IOTBMS
        vrf_vni: 201
        vtep_diagnostic:
          loopback: 20
          loopback_ip_range: 167.84.63.112/24
        evpn_l3_multicast:
          enabled: false
        svis:
          - id: 610
            profile: IOTBMS_default
            name: IOT_WIRELESS
            enabled: true
            tags: [ LAB_LEAFS, LAB_SERVICE_LEAFS ]
            ip_address_virtual: 10.150.0.1/24
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
          # - id: 520
          #   profile: IOTBMS_default
          #   name: BMS_SEGMENT_520
          #   enabled: true
          #   tags: [ LAB_SERVICE_LEAFS ]
          #   ip_address_virtual: 10.142.197.1/25
          #   bgp:
          #     structured_config:
          #       redistribute_routes: [ dot1x ]
          # - id: 521
          #   profile: IOTBMS_default
          #   name: BMS_SEGMENT_521
          #   enabled: true
          #   tags: [ LAB_SERVICE_LEAFS ]
          #   ip_address_virtual: 10.142.197.129/25
          #   bgp:
          #     structured_config:
          #       redistribute_routes: [ dot1x ]
        l3_interfaces:
          # BorderSpine 1 to ASR01 - VLAN 200
          - interfaces: [Ethernet3/48/1.200]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.24/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/0/1_VRF_IOT
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:5::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR01 - VLAN 200
          - interfaces: [Ethernet3/48/1.200]
            nodes: [C000140-014R602P]
            ip_addresses: [10.12.46.10/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/1/5_VRF_IOT
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:2::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 1 to ASR02 - VLAN 200
          - interfaces: [Ethernet4/48/1.200]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.2/31]
            description: P2P_LINK_TO_C160479-003R630A_Gi0/0/1_VRF_IOT
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:11::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR02 - VLAN 200
          - interfaces: [ Ethernet4/48/1.200 ]
            nodes: [ C000140-014R602P ]
            ip_addresses: [10.12.46.18/31]
            description: P2P_LINK_TO_C160479-003R630A_Gi0/1/5_VRF_IOT
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:8::1/127
              flow_tracker:
                sampled: ftr_sampled
        bgp_peers:
          - ip_address: "2000:10:2:5::"
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:11::"
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:17:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:23:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:2::"
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:8::"
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:14:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:20:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          - ip_address: 10.12.46.25
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.3
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE
          # 10.2.17.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.23.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.11
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.19
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE
          # 10.2.14.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.20.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: sd_wan_edge
      - name: VRF_GUEST
        vrf_vni: 301
        vtep_diagnostic:
          loopback: 30
          loopback_ip_range: 167.84.141.160/24
        evpn_l3_multicast:
          enabled: false
        svis:
          - id: 600
            name: Guest_Wireless
            profile: INTERNAL_default
            enabled: true
            tags: [ LAB_LEAFS, LAB_SERVICE_LEAFS ]
            ip_address_virtual: 10.120.40.1/22
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
          - id: 601
            name: Guest_Wired
            profile: INTERNAL_default
            enabled: true
            tags: [ LAB_LEAFS, LAB_SERVICE_LEAFS ]
            ip_address_virtual: 10.120.44.1/22
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
        l3_interfaces:
          # BorderSpine 1 to ASR01 - VLAN 300
          - interfaces: [Ethernet3/48/1.300]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.28/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/0/1_VRF_GUEST
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:6::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR01 - VLAN 300
          - interfaces: [Ethernet3/48/1.300]
            nodes: [C000140-014R602P]
            ip_addresses: [10.12.46.12/31]
            description: P2P_LINK_TO_C160479-003R629A_Gi0/0/1_VRF_GUEST
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:3::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 1 to ASR02 - VLAN 300
          - interfaces: [Ethernet4/48/1.300]
            nodes: [C000140-DCS-7304X3]
            ip_addresses: [10.12.46.4/31]
            description: P2P_LINK_TO__C160479-003R630A_Gi0/1/5_VRF_GUEST
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:12::1/127
              flow_tracker:
                sampled: ftr_sampled
          # BorderSpine 2 to ASR02 - VLAN 300
          - interfaces: [Ethernet4/48/1.300]
            nodes: [C000140-014R602P]
            ip_addresses: [10.12.46.20/31]
            description: P2P_LINK_TO_C160479-003R630A_Gi0/1/5_VRF_GUEST
            structured_config:
              ipv6_enable: true
              ipv6_address: 2000:10:2:9::1/127
              flow_tracker:
                sampled: ftr_sampled
        bgp_peers:
          - ip_address: "2000:10:2:6::"
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:12::"
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:18:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:24:::
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:3::"
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE_IPV6
          - ip_address: "2000:10:2:9::"
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:15:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          # 2000:10:2:21:::
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE_IPV6
          - ip_address: 10.12.46.29
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.5
            nodes: [ C000140-DCS-7304X3 ]
            peer_group: SD_WAN_EDGE
          # 10.2.18.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.24.0:
          #   nodes: [ C000140-DCS-7304X3 ]
          #   peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.13
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE
          - ip_address: 10.12.46.21
            nodes: [ C000140-014R602P ]
            peer_group: SD_WAN_EDGE
          # 10.2.15.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: SD_WAN_EDGE
          # 10.2.21.0:
          #   nodes: [ C000140-014R602P ]
          #   peer_group: sd_wan_edge

    # l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
      # - id: 400
      #   name: MIST_EDGE_CONNECTIVITY
      #   tags: [ LAB_SERVICE_LEAFS ]
      #   evpn_l2_multicast:
      #     enabled: false
      # - id: 1000
      #   name: L2_VLAN1000
      #   evpn_l2_multicast:
      #     enabled: true
      # - id: 1001
      #   name: L2_VLAN1001
      #   evpn_l2_multicast:
      #     enabled: true

# List of Loopback interfaces.
        # This will create Loopback interfaces inside the VRF.
        # Loopbacks:
        #   - node: "C000140-DCS-7304X3"
        #     loopback: 99
        #     ip_address: 10.10.99.99
        #     description: "Anycast RP"
        #     enabled: <bool; default=True>


